apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-agent
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/skarj/ai-agents'
    targetRevision: main
    path: agentic-sre/k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-agents

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
