apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - mcp.yaml
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - resourcequota.yaml
  - services.yaml

# Argo CD Image Updater modifies or appends to this section
images:
  - name: ghcr.io/skarj/ai-agents-agentic-sre
    newName: ghcr.io/skarj/ai-agents-agentic-sre
    newTag: sha-9035aa1
