apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: simple-k8s-agent
  namespace: argocd # Must the same namespace as ArgoCD
spec:
  writeBackConfig:
    # References secret: git:secret:<namespace>/<secret-name>
    method: "git:secret:argocd/github-write-creds"
    gitConfig:
      branch: "main"
      writeBackTarget: "kustomization:."
      user: "argocd-image-updater[bot]"
      email: "argocd-bot@users.noreply.github.com"
  applicationRefs:
    - namePattern: "simple-k8s-agent"
      images:
        - alias: "api"
          imageName: "ghcr.io/skarj/ai-agents-simple-k8s-agent"
          commonUpdateSettings:
            # Sorts matching tags by image creation date in the registry
            updateStrategy: "latest"
            # Matches tags starting with 'sha-' followed by a 7-character hex hash
            allowedTags: "^sha-[a-f0-9]{7}$"
