apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - imageupdater.yaml
  - ollama.yaml
  - pvc.yaml
  - rbac.yaml
  - routes.yaml
  - services.yaml
# Argo CD Image Updater modifies or appends to this section
images:
  - name: ghcr.io/skarj/ai-agents-simple-k8s-agent
    newTag: sha-2ed52eb
